"""CLI entry point for evaluating the trained model on the test set.

Usage::

    python scripts/evaluate.py --model-path checkpoints/best_model.pt
    python scripts/evaluate.py --model-path checkpoints/best_model.pt \\
        --test-dir data/test --output-dir outputs/eval
"""

import argparse
import json
import sys
from pathlib import Path

import torch


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Evaluate a trained corruption classifier on the test set",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    parser.add_argument(
        "--model-path",
        type=Path,
        required=True,
        dest="model_path",
        help="Path to saved .pt checkpoint",
    )
    parser.add_argument(
        "--metadata-csv",
        type=Path,
        default=Path("data/metadata.csv"),
        dest="metadata_csv",
        help="Path to metadata.csv generated by generate_dataset.py",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path("outputs/eval"),
        dest="output_dir",
        help="Directory to save evaluation results",
    )
    parser.add_argument(
        "--batch-size", type=int, default=64, dest="batch_size",
        help="Evaluation batch size"
    )
    parser.add_argument(
        "--device", type=str, default=None,
        help="Device override: 'cpu', 'cuda', 'mps'"
    )
    return parser.parse_args()


def main() -> None:
    """Run evaluation and save a JSON report."""
    import logging
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s | %(levelname)-8s | %(name)s | %(message)s",
        datefmt="%Y-%m-%d %H:%M:%S",
        handlers=[logging.StreamHandler(sys.stdout)],
    )

    args = _parse_args()

    if not args.model_path.exists():
        print(f"ERROR: Checkpoint not found: {args.model_path}", file=sys.stderr)
        sys.exit(1)
    if not args.metadata_csv.exists():
        print(f"ERROR: metadata.csv not found: {args.metadata_csv}", file=sys.stderr)
        sys.exit(1)

    device = torch.device(args.device) if args.device else (
        torch.device("cuda") if torch.cuda.is_available() else torch.device("cpu")
    )

    from src.data.dataset import CLASS_NAMES, create_dataloaders
    from src.inference.predict import load_model_from_checkpoint
    from src.training.metrics import format_metrics_table
    from src.training.trainer import Trainer

    print(f"Loading model from {args.model_path} ...")
    model = load_model_from_checkpoint(args.model_path, device=device)

    print("Loading test data ...")
    loaders = create_dataloaders(
        metadata_csv=args.metadata_csv,
        batch_size=args.batch_size,
        num_workers=4,
        pin_memory=device.type == "cuda",
    )

    # Trainer.evaluate is a stateless helper — we create a minimal instance
    import yaml
    with open("config/default_config.yaml", "r") as fh:
        cfg = yaml.safe_load(fh)

    trainer = Trainer(
        model=model,
        train_loader=loaders["train"],
        val_loader=loaders["val"],
        config=cfg,
        output_dir=args.output_dir,
        device=device,
    )

    print("Evaluating on test set ...")
    _, metrics = trainer.evaluate(loaders["test"], class_names=CLASS_NAMES)

    print("\n" + format_metrics_table(metrics, CLASS_NAMES))

    # Serialise confusion matrix (numpy -> list)
    metrics["confusion_matrix"] = metrics["confusion_matrix"].tolist()

    args.output_dir.mkdir(parents=True, exist_ok=True)
    report_path = args.output_dir / "test_metrics.json"
    with open(report_path, "w", encoding="utf-8") as fh:
        json.dump(metrics, fh, indent=2)
    print(f"\nEvaluation report saved to {report_path}")


if __name__ == "__main__":
    main()
